version: "3"
services:
  db:
    image: postgres:15
    container_name: postgres-api
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api
